routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('admin', 'adminController');
Route::resource('pengumuman', 'PengumumanController');
Route::resource('petugas', 'PetugasController');
Route::resource('barang', 'BarangController');
Route::resource('jenis', 'JenisController');
Route::resource('barangmasuk', 'BrgMasukController');
Route::resource('detailbarangmasuk', 'DetailBrgMasukController');
Route::resource('detailpenjualan', 'DetailPenjualanController');
Route::resource('distributor', 'DistributorController');
Route::resource('penjualan', 'PenjualanController');

resources/views/admin/barang.blade.php
@extends('layouts.master')
@section('content')
<div class="content-wrapper">
	<div class="content">
		<div class="box">
			<div class="box-header">
				<button class="pull-right btn btn-primary" data-toggle="modal" data-target="#AddBarang"><i class="fa fa-plus"></i> New Barang</button>
			</div>
			<div class="box-body">
				<table class="table table-bordered" id="barang">
					<thead>
						<tr>
							<th>No</th>
							<th>Kode Barang</th>
							<th>Nama Barang</th>
							<th>Kode Jenis Barang</th>
							<th>Harga Net</th>
							<th>Harga Jual</th>
							<th>Stok</th>
						</tr>
					</thead>
					<tbody>
						@foreach($allbarang as $bar)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$bar->kodebarang}}</td>
							<td>{{$bar->namabarang}}</td>
							<td>{{$bar->kodejenis}}</td>
							<td>{{$bar->harganet}}</td>
							<td>{{$bar->hargajual}}</td>
							<td>{{$bar->stok}}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="AddBarang" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">New Jenis</h4>
			</div>
			<form action="{{route('barang.store')}}" method="post">
				@csrf
				<div class="modal-body">
					<div class="row">
						<div class="col-md-3">
							<h5>Kode Barang</h5>
						</div>
						<div class="col-md-9">
							<input type="text" class="form-control" name="kodebarang" value="{{rand()}}" readonly>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Nama Barang</h5>
						</div>
						<div class="col-md-9">
							<input type="text" class="form-control" name="namabarang">
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Kode Jenis</h5>
						</div>
						<div class="col-md-9">
							<select class="form-control" name="kodejenis">
								@foreach($alljenis as $jen)
								<option value="{{$jen->kodejenis}}">{{$jen->kodejenis}} | {{$jen->jenis}}</option>
								@endforeach
							</select>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Harga Net</h5>
						</div>
						<div class="col-md-9">
							<input type="number" class="form-control" name="harganet">
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Harga Jual</h5>
						</div>
						<div class="col-md-9">
							<input type="number" class="form-control" name="hargajual">
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Stok</h5>
						</div>
						<div class="col-md-9">
							<input type="number" class="form-control" name="stok">
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-info"><i class="fa fa-save"></i> Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@if(session('alertbarang')){
	<script>
		alert('berhasil menambah barang'+{{ session('alertbarang') }});
	</script>
}
@endif
@endsection
@section('foot-content')
<script>
	$('#barang').DataTable();
</script>
@endsection

resources/views/admin/barangmasuk.blade.php
@extends('layouts.master')
@section('content')
<div class="content-wrapper">
	<div class="content">
		<div class="box box-primary">
			<div class="box-header">Data Barang Masuk
				<button class="pull-right btn btn-primary" data-toggle="modal" data-target="#AddBarangMasuk"><i class="fa fa-plus"></i> New Barang Masuk</button></div>
			<div class="box-body">
				<table class="table table-bordered" id="BarangMasuk">
					<thead>
						<tr>
							<th>No.</th>
							<th>No Nota</th>
							<th>Tanggal Masuk</th>
							<th>ID Distributor</th>
							<th>ID Petugas</th>
							<th>Total</th>
						</tr>
					</thead>
					<tbody>
						@foreach($allbarangmasuk as $b)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$b->nonota}}</td>
							<td>{{$b->tglmasuk}}</td>
							<td>{{$b->iddistributor}}</td>
							<td>{{$b->idpetugas}}</td>
							<td>{{$b->total}}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="AddBarangMasuk" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Barang Masuk</h4>
			</div>
			<form action="{{route('barangmasuk.store')}}" method="post">
				@csrf
				<div class="modal-body">
					<div class="row">
						<div class="col-md-3">
							<h5>No Nota</h5>
						</div>
						<div class="col-md-9">
							<input type="text" class="form-control" name="nonota" value="{{rand()}}" readonly>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Tanggal Masuk</h5>
						</div>
						<div class="col-md-9">
							<input type="date" class="form-control" name="tglmasuk">
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>ID Distributor</h5>
						</div>
						<div class="col-md-9">
							<select class="form-control" name="iddistributor">
								@foreach($alldistributor as $dis)
								<option value="{{$dis->iddistributor}}">{{$dis->iddistributor}} | {{$dis->namadistributor}}</option>
								@endforeach
							</select>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>ID Petugas</h5>
						</div>
						<div class="col-md-9">
							<select class="form-control" name="idpetugas">
								@foreach($allpetugas as $pet)
								<option value="{{$pet->idpetugas}}">{{$pet->idpetugas}} | {{$pet->namapetugas}}</option>
								@endforeach
							</select>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Total</h5>
						</div>
						<div class="col-md-9">
							<input type="number" class="form-control" name="total">
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-info"><i class="fa fa-save"></i> Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection
@section('foot-content')
<script>
	$('#BarangMasuk').DataTable();
</script>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.master')
@section('content')
<div class="content-wrapper">
	<div class="content">
		<div class="row">
			<div class="col-md-3">
				<div class="small-box bg-aqua">
					<div class="inner">
						<h3>{{$allbarang->count()}}</h3>
						<p>Jumlah Barang</p>
					</div>
					<div class="icon">
						<i class="fa fa-truck"></i>
					</div>
					<a href="#" class="small-box-footer">More Info <i class="fa fa-arrow-circle-right"></i></a>
				</div>
			</div>
			<div class="col-md-3">
				<div class="small-box bg-red">
					<div class="inner">
						<h3>{{$allpetugas->count()}}</h3>
						<p>Jumlah Petugas</p>
					</div>
					<div class="icon">
						<i class="fa fa-wrench"></i>
					</div>
					<a href="#" class="small-box-footer">More Info <i class="fa fa-arrow-circle-right"></i></a>
				</div>
			</div>
			<div class="col-md-3">
				<div class="small-box bg-green">
					<div class="inner">
						<h3>{{$alldistributor->count()}}</h3>
						<p>Jumlah Distributor</p>
					</div>
					<div class="icon">
						<i class="fa fa-users"></i>
					</div>
					<a href="#" class="small-box-footer">More Info <i class="fa fa-arrow-circle-right"></i></a>
				</div>
			</div>
			<div class="col-md-3">
				<div class="small-box bg-yellow">
					<div class="inner">
						<h3>{{$alluser->count()}}</h3>
						<p>Jumlah Pengguna</p>
					</div>
					<div class="icon">
						<i class="fa fa-user"></i>
					</div>
					<a href="#" class="small-box-footer">More Info <i class="fa fa-arrow-circle-right"></i></a>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<div class="box box-primary">
					<div class="box-header">Data Barang</div>
					<div class="box-body">
						<table class="table table-bordered" id="barang">
							<thead>
								<tr>
									<th>No</th>
									<th>Nama Barang</th>
									<th>Kode Jenis</th>
									<th>Harga Net</th>
									<th>Harga Jual</th>
									<th>Stok</th>
								</tr>
							</thead>
							<tbody>
								@foreach($allbarang as $brg)
								<tr>
									<td>{{$loop->iteration}}</td>
									<td>{{$brg->namabarang}}</td>
									<td>{{$brg->kodejenis}}</td>
									<td>{{$brg->harganet}}</td>
									<td>{{$brg->hargajual}}</td>
									<td>{{$brg->stok}}</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="box box-warning">
					<div class="box-header">Pengumuman</div>
					<div class="box-body">
						<div class="chat" id="chat-box">
							@foreach($allpengumuman as $peng)
							<div class="item">
								<img src="{{asset('template/dist/img/user2-160x160.jpg')}}">
								<p class="message">
									{{$peng->pengumuman}}<br>
									<small style="color: silver">By: {{$peng->author}}</small>
									<small class="text-muted pull-right">{{$peng->created_at}}</small>
								</p>
							</div>
							@endforeach
						</div>
					</div>
					<div class="box-footer">
						<form method="post" action="{{route('pengumuman.store')}}">
							@csrf
			                <div class="input-group">
			                  <input type="hidden" name="author" value="{{ucfirst(Auth::user()->name)}}">
			                  <input class="form-control" placeholder="Type Announce" name="pengumuman">
			                  <div class="input-group-btn">
			                    <button type="submit" class="btn btn-success"><i class="fa fa-plus"></i></button>
			                  </div>
			                </div>
			            </form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('foot-content')
<script>
	$('#barang').DataTable();
	$('#petugas').DataTable();
	$('#user').DataTable();
</script>
@endsection

resources/views/admin/detailbarang.blade.php
@extends('layouts.master')
@section('content')
<div class="content-wrapper">
	<div class="content">
		<div class="box">
			<div class="box-header">
				<button class="pull-right btn btn-primary" data-toggle="modal" data-target="#NewDetailBarangMasuk"><i class="fa fa-plus"></i> New Detail Barang</button>
			</div>
			<div class="box-body">
				<table class="table table-bordered" id="DetailBarangMasuk">
					<thead>
						<tr>
							<th>No</th>
							<th>No Nota</th>
							<th>Kode Barang</th>
							<th>Jumlah</th>
							<th>Subtotal</th>
						</tr>
					</thead>
					<tbody>
						@foreach($detailbarangmasuk as $d)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$d->nonota}}</td>
							<td>{{$d->kodebarang}}</td>
							<td>{{$d->jumlah}}</td>
							<td>{{$d->subtotal}}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="NewDetailBarangMasuk" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Barang Masuk</h4>
			</div>
			<form action="{{route('detailbarangmasuk.store')}}" method="post">
				@csrf
				<div class="modal-body">
					<div class="row">
						<div class="col-md-3">
							<h5>No Nota</h5>
						</div>
						<div class="col-md-9">
							<select class="form-control" name="nonota">
								@foreach($allbarangmasuk as $barmas)
								<option>{{$barmas->nonota}}</option>
								@endforeach()
							</select>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Kode Barang</h5>
						</div>
						<div class="col-md-9">
							<select class="form-control" name="kodebarang">
								@foreach($allbarang as $bar)
								<option value="{{$bar->kodebarang}}">{{$bar->kodebarang}} | {{$bar->namabarang}}</option>
								@endforeach
							</select>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Jumlah</h5>
						</div>
						<div class="col-md-9">
							<input type="number" class="form-control" name="jumlah">
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Subtotal</h5>
						</div>
						<div class="col-md-9">
							<input type="number" class="form-control" name="subtotal">
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-info"><i class="fa fa-save"></i> Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection
@section('foot-content')
<script>
	$('#DetailBarangMasuk').DataTable();
</script>
@endsection

resources/views/admin/detailpenjualan.blade.php
@extends('layouts.master')
@section('content')
<div class="content-wrapper">
	<div class="content">
		<div class="box">
			<div class="box-header">
				<button class="pull-right btn btn-primary" data-toggle="modal" data-target="#AddDetailPenjualan"><i class="fa fa-plus"></i> New Detail Penjualan</button>
			</div>
			<div class="box-body">
				<table class="table table-bordered" id="DetailPenjualan">
					<thead>
						<tr>
							<th>No</th>
							<th>Nomor Faktur</th>
							<th>Kode Barang</th>
							<th>Jumlah</th>
							<th>Subtotal</th>
						</tr>
					</thead>
					<tbody>
						@foreach($alldetailpenjualan as $p)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$p->nofaktur}}</td>
							<td>{{$p->kodebarang}}</td>
							<td>{{$p->jumlah}}</td>
							<td>{{$p->subtotal}}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection
@section('foot-content')
<script>
	$('#DetailPenjualan').DataTable();
</script>
@endsection

resources/views/admin/distributor.blade.php
@extends('layouts.master')
@section('content')
<div class="content-wrapper">
	<div class="content">
		<div class="box">
			<div class="box-header">
				<button class="pull-right btn btn-primary" data-toggle="modal" data-target="#AddDistributor"><i class="fa fa-plus"></i> New Distributor</button>
			</div>
			<div class="box-body">
				<table class="table table-bordered" id="Distributor">
					<thead>
						<tr>
							<th>No</th>
							<th>ID Distributor</th>
							<th>Nama Distributor</th>
							<th>Alamat</th>
							<th>Kota Asal</th>
							<th>Email</th>
							<th>No Telp</th>
						</tr>
					</thead>
					<tbody>
						@foreach($alldistributor as $d)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$d->iddistributor}}</td>
							<td>{{$d->namadistributor}}</td>
							<td>{{$d->alamat}}</td>
							<td>{{$d->kotaasal}}</td>
							<td>{{$d->email}}</td>
							<td>{{$d->telpon}}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="AddDistributor" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">New Distributor</h4>
			</div>
			<form action="{{route('distributor.store')}}" method="post">
				@csrf
				<div class="modal-body">
					<div class="row">
						<div class="col-md-3">
							<h5>ID Distributor</h5>
						</div>
						<div class="col-md-9">
							<input type="text" class="form-control" name="iddistributor" placeholder="ID Distributor" readonly value="{{rand()}}">
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Nama Distributor</h5>
						</div>
						<div class="col-md-9">
							<input type="text" class="form-control" name="namadistributor" placeholder="Nama Distributor" required>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Alamat</h5>
						</div>
						<div class="col-md-9">
							<textarea class="form-control" rows="3" name="alamat" placeholder="Alamat" required></textarea>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Kota Asal</h5>
						</div>
						<div class="col-md-9">
							<input type="text" class="form-control" name="kotaasal" placeholder="Kota Asal" required>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Email</h5>
						</div>
						<div class="col-md-9">
							<input type="email" class="form-control" name="email" placeholder="Email" required>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Nomor Telepon</h5>
						</div>
						<div class="col-md-9">
							<input type="number" class="form-control" name="telpon" placeholder="Nomor Telepon" required>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-info"><i class="fa fa-save"></i> Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection
@section('foot-content')
<script>
	$('#Distributor').DataTable();
</script>
@endsection

resources/views/admin/jenis.blade.php
@extends('layouts.master')
@section('content')
<div class="content-wrapper">
	<div class="content">
		<div class="box">
			<div class="box-header">
				<button class="pull-right btn btn-primary" data-toggle="modal" data-target="#AddJenis"><i class="fa fa-plus"></i> New Jenis</button>
			</div>
			<div class="box-body">
				<table class="table table-bordered" id="Jenis">
					<thead>
						<tr>
							<th>No</th>
							<th>Kode Jenis</th>
							<th>Jenis</th>
						</tr>
					</thead>
					<tbody>
						@foreach($alljenis as $p)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$p->kodejenis}}</td>
							<td>{{$p->jenis}}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="AddJenis" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">New Jenis</h4>
			</div>
			<form action="{{route('jenis.store')}}" method="post">
				@csrf
				<div class="modal-body">
					<div class="row">
						<div class="col-md-3">
							<h5>Kode Jenis</h5>
						</div>
						<div class="col-md-9">
							<input type="text" class="form-control" name="kodejenis" value="{{rand()}}" readonly>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Jenis</h5>
						</div>
						<div class="col-md-9">
							<input type="text" class="form-control" name="jenis">
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-info"><i class="fa fa-save"></i> Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection
@section('foot-content')
<script>
	$('#Jenis').DataTable();
</script>
@endsection

resources/views/admin/penjualan.blade.php
@extends('layouts.master')
@section('content')
<div class="content-wrapper">
	<div class="content">
		<div class="box">
			<div class="box-header">
				<button class="pull-right btn btn-primary" data-toggle="modal" data-target="#AddPenjualan"><i class="fa fa-plus"></i> New Penjualan</button>
			</div>
			<div class="box-body">
				<table class="table table-bordered" id="penjualan">
					<thead>
						<tr>
							<th>No</th>
							<th>Nomor Faktur</th>
							<th>Tanggal Penjualan</th>
							<th>ID Petugas</th>
						</tr>
					</thead>
					<tbody>
						@foreach($allpenjualan as $p)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$p->nofaktur}}</td>
							<td>{{$p->tglpenjualan}}</td>
							<td>{{$p->idpetugas}}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="AddPenjualan" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">New Penjualan</h4>
			</div>
			<form action="{{route('penjualan.store')}}" method="post">
				@csrf
				<div class="modal-body">
					<div class="row">
						<div class="col-md-3">
							<h5>Nomor Faktur</h5>
						</div>
						<div class="col-md-9">
							<input type="text" class="form-control" name="nofaktur" value="LRS{{rand()}}" readonly>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Tanggal Penjualan</h5>
						</div>
						<div class="col-md-9">
							<input type="date" class="form-control" name="tglpenjualan">
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>ID Petugas</h5>
						</div>
						<div class="col-md-9">
							<select class="form-control" name="idpetugas">
								@foreach($allpetugas as $pet)
								<option value="{{$pet->idpetugas}}">{{$pet->idpetugas}} | {{$pet->namapetugas}}</option>
								@endforeach
							</select>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-info"><i class="fa fa-save"></i> Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection
@section('foot-content')
<script>
	$('#penjualan').DataTable();
</script>
@endsection

resources/views/admin/petugas.blade.php
@extends('layouts.master')
@section('content')
<div class="content-wrapper">
	<div class="content">
		<div class="box">
			<div class="box-header">
				<button class="pull-right btn btn-primary" data-toggle="modal" data-target="#AddPetugas"><i class="fa fa-plus"></i> New Petugas</button>
			</div>
			<div class="box-body">
				<table class="table table-bordered" id="petugas">
					<thead>
						<tr>
							<th>No</th>
							<th>ID Petugas</th>
							<th>Nama Petugas</th>
							<th>Alamat Petugas</th>
							<th>Email Petugas</th>
							<th>No. Telepon Petugas</th>
						</tr>
					</thead>
					<tbody>
						@foreach($allpetugas as $p)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$p->idpetugas}}</td>
							<td>{{$p->namapetugas}}</td>
							<td>{{$p->alamat}}</td>
							<td>{{$p->email}}</td>
							<td>{{$p->telpon}}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="AddPetugas" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">New Petugas</h4>
			</div>
			<form action="{{route('petugas.store')}}" method="post">
				@csrf
				<div class="modal-body">
					<div class="row">
						<div class="col-md-3">
							<h5>ID Petugas</h5>
						</div>
						<div class="col-md-9">
							<input type="text" class="form-control" name="idpetugas" readonly value="{{rand()}}">
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Nama Petugas</h5>
						</div>
						<div class="col-md-9">
							<input type="text" class="form-control" name="namapetugas" placeholder="Nama Petugas" required>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Alamat</h5>
						</div>
						<div class="col-md-9">
							<textarea class="form-control" rows="3" name="alamat" placeholder="Alamat" required></textarea>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Email</h5>
						</div>
						<div class="col-md-9">
							<input type="email" class="form-control" name="email" placeholder="Email" required>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<h5>Nomor Telepon</h5>
						</div>
						<div class="col-md-9">
							<input type="number" class="form-control" name="telpon" placeholder="Nomor Telepon" required>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-info"><i class="fa fa-save"></i> Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection
@section('foot-content')
<script>
	$('#petugas').DataTable();
</script>
@endsection